// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiVetenary.Data.Models
{
    public partial class Animal
    {
        public Animal()
        {
            AppointmentDetails = new HashSet<AppointmentDetail>();
            MedicalRecords = new HashSet<MedicalRecord>();
        }

        public int AnimalId { get; set; }
        public int? OwnerId { get; set; }
        public string Name { get; set; }
        public string Species { get; set; }
        public int? TypeId { get; set; }
        public string Origin { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public int? Age { get; set; }
        public decimal? Weight { get; set; }
        public decimal? Length { get; set; }
        public string Color { get; set; }
        public string DistinguishingMarks { get; set; }
        public DateTime? DateAdded { get; set; }
        public DateTime? LastCheckup { get; set; }
        public string ImageUrl { get; set; }
        public string Gender { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual Owner Owner { get; set; }
        public virtual AnimalType Type { get; set; }
        public virtual ICollection<AppointmentDetail> AppointmentDetails { get; set; }
        public virtual ICollection<MedicalRecord> MedicalRecords { get; set; }
    }
}