// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiVetenary.Data.Models
{
    public partial class MedicalRecord
    {
        public int RecordId { get; set; }
        public int? AnimalId { get; set; }
        public DateTime? RecordDate { get; set; }
        public string Symptoms { get; set; }
        public string Diagnosis { get; set; }
        public string Treatment { get; set; }
        public string Medications { get; set; }
        public string LabResults { get; set; }
        public string VetNotes { get; set; }
        public bool? FollowUpRequired { get; set; }
        public DateTime? FollowUpDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual Animal Animal { get; set; }
    }
}