// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiVetenary.Data.Models
{
    public partial class Payment
    {
        public int PaymentId { get; set; }
        public int? AppointmentId { get; set; }
        public DateTime? PaymentDate { get; set; }
        public double? TotalAmount { get; set; }
        public string TransactionNo { get; set; }
        public string BankTranNo { get; set; }
        public string ResponseCode { get; set; }
        public string TransactionStatus { get; set; }
        public DateTime? CreatedAt { get; set; }
        public string ResponseId { get; set; }
        public string TmnCode { get; set; }
        public string TxnRef { get; set; }
        public long Amount { get; set; }
        public string OrderInfo { get; set; }
        public string Message { get; set; }
        public DateTime PayDate { get; set; }
        public string BankCode { get; set; }
        public string TransactionType { get; set; }
        public string SecureHash { get; set; }

        public virtual Appointment Appointment { get; set; }
    }
}